```{r setup, include=FALSE}
#load packages
library(tidyr)
library(dplyr)
library(ggplot2)
library(readxl)
library(caret)
library(pROC)
```

```{r}
#load the data
credit <- read_excel("default of credit card clients.xls")
credit <- credit[ , -1]
str(credit)
```

```{r}
#factorization
credit$SEX <- as.factor(credit$SEX)
credit$EDUCATION <- as.factor(credit$EDUCATION)
credit$MARRIAGE <- as.factor(credit$MARRIAGE)
credit$PAY_0 <- as.factor(credit$PAY_0)
credit$PAY_2 <- as.factor(credit$PAY_2)
credit$PAY_3 <- as.factor(credit$PAY_3)
credit$PAY_4 <- as.factor(credit$PAY_4)
credit$PAY_5 <- as.factor(credit$PAY_5)
credit$PAY_6 <- as.factor(credit$PAY_6)
credit$`default payment next month` <- as.factor(credit$`default payment next month`)
```

```{r}
#data cleaning
#PAY
credit$PAY_0[credit$PAY_0 == -2] <- -1
credit$PAY_0[credit$PAY_0 == 0] <- -1
credit$PAY_2[credit$PAY_2 == -2] <- -1
credit$PAY_2[credit$PAY_2 == 0] <- -1
credit$PAY_3[credit$PAY_3 == -2] <- -1
credit$PAY_3[credit$PAY_3 == 0] <- -1
credit$PAY_4[credit$PAY_4 == -2] <- -1
credit$PAY_4[credit$PAY_4 == 0] <- -1
credit$PAY_5[credit$PAY_5 == -2] <- -1
credit$PAY_5[credit$PAY_5 == 0] <- -1
credit$PAY_6[credit$PAY_6 == -2] <- -1
credit$PAY_6[credit$PAY_6 == 0] <- -1

#EDUCATION
credit$EDUCATION[credit$EDUCATION == 0] <- 4
credit$EDUCATION[credit$EDUCATION == 5] <- 4
credit$EDUCATION[credit$EDUCATION == 6] <- 4

#MARRIAGE
credit$MARRIAGE[credit$MARRIAGE == 0] <- 3

str(credit)
```

```{r}
#normalization for numerical columns
col <- c(1, 5, 12 : 23)

#scale
for(i in col) {
  credit[ , i] <- apply(credit[ , i], 2, function(x) (x - mean(x)) / sd(x))
}

#center
for(i in col) {
  credit[ , i] <- apply(credit[ , i], 2, function(x) (x - mean(x)))
}

str(credit)
```

```{r}
#sampling
set.seed(123)
train.index <- sample(c(1 : 30000), 18000) #60% training, 40% testing
```

```{r}
#feature selection
selected.var0 <- c(1 : 24) #significant variables
train.df0 <- credit[train.index, selected.var0]
valid.df0 <- credit[-train.index, selected.var0]

log_res0 <- glm(data = credit, family = "binomial",
               formula = `default payment next month` ~ LIMIT_BAL + SEX + EDUCATION + MARRIAGE + AGE +
                 PAY_0 + PAY_2 + PAY_3 + PAY_4 + PAY_5 + PAY_6 +
                 BILL_AMT1 + BILL_AMT2 + BILL_AMT3 + BILL_AMT4 + BILL_AMT5 + BILL_AMT6 +
                 PAY_AMT1 + PAY_AMT2 + PAY_AMT3 + PAY_AMT4 + PAY_AMT5 + PAY_AMT6)
summary(log_res0)

log_predictions0 <- as.data.frame(predict(log_res0, valid.df0, type = "response"))
pre_res0 <- ifelse(log_predictions0 >= 0.5, 1, 0)
pre_tb0 <- table(pre_res0, as.matrix(valid.df0[ , 24]))
accuracy0 <- sum(diag(pre_tb0)) / sum(pre_tb0)

pre_tb0
accuracy0
```

```{r}
#dataset
selected.var <- c(-12, -13, -14, -15, -16, -17) #significant variables
train.df <- credit[train.index, selected.var]
valid.df <- credit[-train.index, selected.var]
```

```{r}
#Logistic Regression
log_res <- glm(data = credit, family = "binomial",
               formula = `default payment next month` ~ LIMIT_BAL + SEX + EDUCATION + MARRIAGE + AGE +
                 PAY_0 + PAY_2 + PAY_3 + PAY_4 + PAY_5 + PAY_6 +
                 PAY_AMT1 + PAY_AMT2 + PAY_AMT3 + PAY_AMT4 + PAY_AMT5 + PAY_AMT6)
summary(log_res)
```

```{r}
#prediction
log_predictions <- as.data.frame(predict(log_res, valid.df, type = "response"))
pre_res <- ifelse(log_predictions >= 0.5, 1, 0)
pre_tb <- table(pre_res, as.matrix(valid.df[ , 18]))
accuracy <- sum(diag(pre_tb)) / sum(pre_tb)

log_predictions %>% head(30) %>% tail(20)
pre_res %>% head(30) %>% tail(20)
pre_tb
accuracy
```

```{r}
#confusion matrix
res_mat <- confusionMatrix(as.factor(pre_res), as.factor(as.matrix(valid.df[ , 18])))
res_mat

#ROC curve
log_pre <- predict(log_res, valid.df, type = "response")
roccurve <- roc(valid.df$`default payment next month` ~ log_pre)
plot(roccurve)
auc(roccurve)
```

```{r}
#ROC curve
plot(roccurve, print.auc = TRUE, auc.polygon = TRUE, legacy.axes = TRUE,
     grid = c(0.1, 0.2), grid.col = c("green", "red"), max.auc.polygon = TRUE,
     auc.polygon.col = "skyblue", print.thres = TRUE)
```
